version: "3.2"
services:
  frontend:
    image: test-rental-frontend
    ports:
      - "3000:3000"
    build:
      context: ./tesla-frontend
      dockerfile: Dockerfile

  backend:
    image: test-rental-backend
    ports:
      - "5031:8080"
    build:
      context: .
      dockerfile: Workshop.API/Dockerfile
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "yourRootPassword"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10


